
Data Analysis

```{r}
library(stringr)
text1 = readLines("data_cpu.txt")
text2 = readLines("data_gpu.txt")
#length(text1)
```


```{r}
data.frame(df, stringsAsFactors = TRUE)

size <- c(sub(".*: ", "", text1[1]))
kernel <- c(sub(".*: ", "", text1[2]))
time <- c(sub(".*: ", "", text1[3]))
gflops <- c(sub(".*: ", "", text1[4]))
choice <- c("cpu")
for (i in seq(5, length(text1), by=4)) {
  size[i/4 + 1] = sub(".*: ", "", text1[i])
  kernel[i/4 + 1] = sub(".*: ", "", text1[i+1])
  choice[i/4 + 1] = "cpu"
  time[i/4 + 1] = sub(".*: ", "", text1[i+2])
  gflops[i/4 + 1] = sub(".*: ", "", text1[i+3])
}

m= length(size)

for (i in seq(1, length(text2), by=5)) {
  size[i/5 + 1+m] = sub(".*: ", "", text2[i])
  kernel[i/5 + 1+m] = sub(".*: ", "", text2[i+1])
  if(sub(".*: ", "", text2[i+2])==1){
    choice[i/5 + 1+m] = "naive"
  }else{
    choice[i/5 + 1+m] ="tiled"
  }
  
  time[i/5 + 1+m] = sub(".*: ", "", text2[i+3])
  gflops[i/5 + 1+m] = sub(".*: ", "", text2[i+4])
}
df <- data.frame(size,kernel,choice, time,gflops)

df
```
```{r}
df
df$size <- as.numeric(as.character(df$size))
df$kernel <- as.numeric(as.character(df$kernel))
df$time <- as.numeric(as.character(df$time))
df$gflops <- as.numeric(as.character(df$gflops))

df <- df[df$kernel == 3,]
df
```


```{r}
library(ggplot2)
sp<-ggplot(df, aes(x=size, y=time, color=choice)) + geom_point() + theme_bw() + geom_path(aes(group = choice)) 
sp + scale_y_log10()
sp
```


```{r}
df0 <- df[df$choice == 0,]$time
df1 <- df[df$choice == 1,]$time
df2 <- df[df$choice == 2,]

ggplot(df, aes(x=Size)) + 
  geom_line(aes(y = df0), color = "darkred")
```






```{r}
tu <- expand.grid(choice   = gl(3, 1, labels = c('0', '1', '2')))


ggplot(tu, aes(x = Size, y = time, color = choice, group = choice)) + 
  geom_point() + geom_line() 

```


```{r}
sp <- ggscatter(df, x = "Size", y = "time",
                add = "reg.line",               # Add regression line
                conf.int = TRUE,                # Add confidence interval
                color = "choice", palette = "jco", # Color by groups "cyl"
                shape = "choice"                   # Change point shape by groups "cyl"
                )+
  stat_cor(aes(color = choice), label.x = 3)       # Add correlation coefficient
sp
```

We want to show the evolution of time depending on the size and the kernel.

```{r}
plot(df$Size,df$Time)
#col=c("red","blue","green")[df$Kernel])
```


```{r}
library(ggplot2)
p <- ggplot(df, aes(x = Size, y = Time)) + 
  geom_point() 
p + scale_y_log10()
p + scale_y_continuous(trans = "log10")
p + geom_line()
```

```{r}
df %>% filter(df$Kernel = 3)
df